"""Render one keyword guide per search channel from the shared catalog.

Manual setup records accepted phrases and private additions per channel.
Search reads the reviewed catalog and local overlay.
"""

from __future__ import annotations

import argparse
import json
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "config/timeline-search-keywords.json"
LOCAL = ROOT / "accounts/search-keywords.json"
CHANNELS = (
    ("x", "X", "X"),
    ("linkedin", "linkedin", "linkedin"),
    ("hacker_news", "HackerNews", "Hacker News"),
    ("github", "GitHub", "GitHub"),
    ("product_hunt", "ProductHunt", "Product Hunt"),
)
CHANNEL_KEYS = tuple(key for key, _folder, _label in CHANNELS)
PHRASE_COUNT = 5
TARGET = (
    "Target is **AI assistant developers and AI agent developers** — people shipping "
    "an assistant, agent, MCP server, tool loop, eval, or memory. A generic software "
    "developer, consumer ChatGPT/Claude use, or a hiring blast is not a hit."
)
PROCEDURE = {
    "x": "Use the bounded X provider search; inspect the original post and author context.",
    "linkedin": "Use the selected Human Discovery source contract. A profile alone is not a replyable post.",
    "hacker_news": "Preserve the exact item and author identity. Human Reply owns any public response.",
    "github": "Preserve repository provenance and developer identity; exclude bots and unverified owners.",
    "product_hunt": "Keep a maker profile and launch URL; a product page alone does not identify a person.",
}


def phrases(catalog, channel):
    return [entry[channel] for entry in catalog["entries"]]


def render(catalog, channel):
    names = {key: label for key, _folder, label in CHANNELS}
    if channel not in names:
        raise ValueError("Expected a search channel")
    terms = phrases(catalog, channel)
    if len(terms) != PHRASE_COUNT or len(set(term.casefold() for term in terms)) != PHRASE_COUNT:
        raise ValueError(f"Exactly {PHRASE_COUNT} distinct phrases required per platform")
    if any(entry["x"] != entry["linkedin"] for entry in entries(catalog)):
        raise ValueError("Both platforms must use the same literal phrases")
    if any(entry[channel] != entry["x"] for entry in entries(catalog)):
        raise ValueError("Search channels must use the same assistant-developer phrases")
    platform = names[channel]
    lines = [
        f"# {platform}: {PHRASE_COUNT} assistant AI developer keywords",
        "",
        f"Version **{catalog['version']}** · Reviewed **{catalog['reviewed_at']}**.",
        "",
        TARGET,
        "",
        "Reviewed discovery terms, not measured search-volume rankings.",
        "",
        "## Search procedure",
        "",
        PROCEDURE[channel],
        "",
        "Run manually within the selected agent scope. Record catalog version, exact query, "
        "provider/account identity, source URL, time and coverage gaps. Search never authorizes outreach.",
        "",
        "## Keywords",
        "",
        "Numbers indicate editorial priority, not search volume. Evidence supports "
        "assistant/agent-builder relevance and terminology; it does not prove popularity.",
        "",
        "| Priority | ID | Literal keyword | Evidence |",
        "|---|---|---|---|",
    ]
    for entry in catalog["entries"]:
        references = ", ".join(
            f"[{key}]({catalog['sources'][key]['url']})" for key in entry["evidence"]
        )
        lines.append(f"| {entry['priority']} | {entry['id']} | `{entry[channel]}` | {references} |")
    lines += [
        "",
        "## Review and updates",
        "",
        "Keep people building assistants distinct from people merely using an AI tool. "
        "Read actual context; reject unrelated job titles, marketing-only claims and identity "
        "conflicts. Prepare qualified CRM handoffs for Ops and preserve source evidence. "
        "Human Reply owns contextual public replies under its separate platform contract.",
        "",
        "Generated by `crm.keyword_docs` from the JSON catalog. Edit the catalog and regenerate "
        "every channel guide together. Retain prior-version receipts; do not count them as "
        "fresh coverage of a revised catalog.",
        "",
    ]
    return "\n".join(lines)


def entries(catalog):
    return catalog["entries"]


def channel_meta(channel):
    for key, folder, label in CHANNELS:
        if key == channel:
            return {"channel": key, "folder": folder, "label": label}
    raise ValueError("Expected a search channel")


def empty_local(catalog_version):
    return {
        "schema_version": 1,
        "catalog_version": catalog_version,
        "updated_at": None,
        "channels": {
            key: {
                "status": "pending",
                "accepted_at": None,
                "accepted_catalog_version": None,
                "added": [],
            }
            for key in CHANNEL_KEYS
        },
    }


def load_local(path=LOCAL, catalog_version=""):
    path = Path(path)
    if not path.is_file():
        return empty_local(catalog_version)
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError:
        return empty_local(catalog_version)
    if not isinstance(data, dict):
        return empty_local(catalog_version)
    base = empty_local(catalog_version)
    base["catalog_version"] = data.get("catalog_version") or catalog_version
    base["updated_at"] = data.get("updated_at")
    incoming = data.get("channels") if isinstance(data.get("channels"), dict) else {}
    for key in CHANNEL_KEYS:
        row = incoming.get(key) if isinstance(incoming.get(key), dict) else {}
        added = [str(phrase).strip() for phrase in (row.get("added") or []) if str(phrase).strip()]
        base["channels"][key] = {
            "status": "accepted" if row.get("status") == "accepted" else "pending",
            "accepted_at": row.get("accepted_at"),
            "accepted_catalog_version": row.get("accepted_catalog_version"),
            "added": added,
        }
    return base


def write_local(data, path=LOCAL):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")
    path.chmod(0o600)
    return path


def channel_state(row, catalog_version):
    if row.get("status") != "accepted":
        return "pending"
    if row.get("accepted_catalog_version") != catalog_version:
        return "stale"
    return "accepted"


HOURLY_WINDOW = {
    "x": "last hour, Apify",
    "linkedin": "last hour, Apify",
    "hacker_news": "last hour, Apify",
    "github": "last hour, Apify",
    "product_hunt": "today's launches, Apify",
}


def hourly_line(label, shipped, added, window):
    listed = "; ".join(f"`{phrase}`" for phrase in shipped)
    extra = ""
    if added:
        extra = " Plus local extras: " + "; ".join(f"`{phrase}`" for phrase in added) + "."
    return (
        f"Hourly search will query {label} for these {PHRASE_COUNT} phrases "
        f"({window}): {listed}.{extra}"
    )


def show_channel(channel, *, catalog=None, local=None, catalog_path=CATALOG, local_path=LOCAL):
    meta = channel_meta(channel)
    catalog = catalog or json.loads(Path(catalog_path).read_text())
    local = local or load_local(local_path, catalog.get("version", ""))
    row = local["channels"][channel]
    shipped = phrases(catalog, channel)
    added = list(row.get("added") or [])
    window = HOURLY_WINDOW[channel]
    return {
        "channel": channel,
        "label": meta["label"],
        "keywords_md": f"runtime/{meta['folder']}/KEYWORDS.md",
        "local_setup": f"runtime/{meta['folder']}/LOCAL_SETUP.md",
        "catalog_version": catalog.get("version"),
        "status": channel_state(row, catalog.get("version")),
        "shipped": shipped,
        "added": added,
        "hourly": hourly_line(meta["label"], shipped, added, window),
        "window": window,
        "prompt": (
            f"Hourly search will run these {PHRASE_COUNT} on {meta['label']} every hour. "
            "Accept them, or name phrases to add. Extras stay in private local setup."
        ),
    }


def show_all(*, catalog=None, local=None, catalog_path=CATALOG, local_path=LOCAL):
    catalog = catalog or json.loads(Path(catalog_path).read_text())
    local = local or load_local(local_path, catalog.get("version", ""))
    return {
        "catalog_version": catalog.get("version"),
        "local_path": "runtime/accounts/search-keywords.json",
        "channels": [
            show_channel(
                key,
                catalog=catalog,
                local=local,
                catalog_path=catalog_path,
                local_path=local_path,
            )
            for key in CHANNEL_KEYS
        ],
    }


def add_phrase(channel, phrase, *, catalog_path=CATALOG, local_path=LOCAL):
    channel_meta(channel)
    phrase = (phrase or "").strip()
    if not phrase:
        raise ValueError("Phrase required")
    catalog = json.loads(Path(catalog_path).read_text())
    shipped = {term.casefold() for term in phrases(catalog, channel)}
    local = load_local(local_path, catalog.get("version", ""))
    row = local["channels"][channel]
    existing = {term.casefold() for term in row["added"]}
    if phrase.casefold() in shipped or phrase.casefold() in existing:
        raise ValueError("Phrase already listed")
    row["added"].append(phrase)
    local["catalog_version"] = catalog.get("version")
    local["updated_at"] = datetime.now(timezone.utc).isoformat()
    write_local(local, local_path)
    return show_channel(
        channel, catalog=catalog, local=local, catalog_path=catalog_path, local_path=local_path
    )


def accept_channel(channel, *, catalog_path=CATALOG, local_path=LOCAL):
    channel_meta(channel)
    catalog = json.loads(Path(catalog_path).read_text())
    local = load_local(local_path, catalog.get("version", ""))
    now = datetime.now(timezone.utc).isoformat()
    local["channels"][channel]["status"] = "accepted"
    local["channels"][channel]["accepted_at"] = now
    local["channels"][channel]["accepted_catalog_version"] = catalog.get("version")
    local["catalog_version"] = catalog.get("version")
    local["updated_at"] = now
    write_local(local, local_path)
    return show_channel(
        channel, catalog=catalog, local=local, catalog_path=catalog_path, local_path=local_path
    )


def status(*, catalog_path=CATALOG, local_path=LOCAL):
    payload = show_all(catalog_path=catalog_path, local_path=local_path)
    rows = payload["channels"]
    return {
        "catalog_version": payload["catalog_version"],
        "local_path": payload["local_path"],
        "ready": all(row["status"] == "accepted" for row in rows),
        "channels": {
            row["channel"]: {
                "status": row["status"],
                "added": len(row["added"]),
                "local_setup": row["local_setup"],
            }
            for row in rows
        },
    }


def load_search_catalog(*, catalog_path=CATALOG, local_path=LOCAL, catalog=None, local=None):
    """Shipped catalog plus per-channel extras from private local setup."""
    catalog = (
        deepcopy(catalog) if catalog is not None else json.loads(Path(catalog_path).read_text())
    )
    version = catalog.get("version", "")
    local = local if local is not None else load_local(local_path, version)
    extras = []
    for offset, channel in enumerate(CHANNEL_KEYS, start=1):
        added = (local.get("channels") or {}).get(channel, {}).get("added") or []
        for index, phrase in enumerate(added, start=1):
            entry = {
                "id": f"LOCAL-{channel}-{index:02d}",
                "family": "LOCAL",
                "priority": 100 + offset * 10 + index,
                "local": True,
                "rationale": "Operator addition during Cursor setup",
            }
            for key in CHANNEL_KEYS:
                entry[key] = phrase if key == channel else ""
            extras.append(entry)
    catalog["entries"] = list(catalog.get("entries") or []) + extras
    catalog["local_added"] = len(extras)
    return catalog


def render_guides(catalog=None):
    catalog = catalog or json.loads(CATALOG.read_text())
    for channel, folder, _label in CHANNELS:
        dest = ROOT / folder / "KEYWORDS.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render(catalog, channel))
    return catalog["version"]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command",
        nargs="?",
        default="render",
        choices=("render", "show", "accept", "add", "status"),
    )
    parser.add_argument("--channel")
    parser.add_argument("--phrase")
    args = parser.parse_args(argv)
    if args.command == "render":
        version = render_guides()
        print(f"Rendered {len(CHANNELS)} keyword guides for {version}")
        return
    if args.command == "status":
        print(json.dumps(status(), indent=2))
        return
    if args.command == "show":
        if args.channel:
            print(json.dumps(show_channel(args.channel), indent=2))
            return
        print(json.dumps(show_all(), indent=2))
        return
    if not args.channel:
        parser.error("--channel is required")
    if args.command == "add":
        print(json.dumps(add_phrase(args.channel, args.phrase), indent=2))
        return
    print(json.dumps(accept_channel(args.channel), indent=2))


if __name__ == "__main__":
    main()
