"""Explicit, non-destructive CRM namespace migration and exact readback."""

import argparse
import hashlib
import json
import re
import sqlite3
from pathlib import Path

from crm.database import (
    APPEND_ONLY,
    IDENTITIES,
    PRIVATE_COLUMNS,
    PRIVATE_TABLES,
    ROOT,
    public_value,
    schema_connection,
    shared_tables,
)


def schema_sql():
    statements = [
        "CREATE SCHEMA crm_gtm",
        "SET LOCAL search_path=crm_gtm,pg_catalog",
        "CREATE TABLE crm_backend_meta(key text PRIMARY KEY,value text NOT NULL)",
        "INSERT INTO crm_backend_meta VALUES('schema_version','1')",
        "CREATE TABLE crm_commits(commit_id text PRIMARY KEY,operator text NOT NULL,operation_count integer NOT NULL,committed_at timestamptz NOT NULL DEFAULT clock_timestamp())",
        """CREATE FUNCTION crm_utc_now() RETURNS text LANGUAGE SQL STABLE AS $$ SELECT to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') $$""",
        "CREATE FUNCTION crm_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'CRM history is append-only'; END $$",
    ]
    for table, spec in shared_tables().items():
        sql = spec["sql"].replace("current_role", '"current_role"')
        sql = re.sub(r"strftime\('%Y-%m-%dT%H:%M:%fZ',\s*'now'\)", "crm_utc_now()", sql)
        sql = sql.replace(" AUTOINCREMENT", "")
        if table in IDENTITIES:
            key = IDENTITIES[table]
            sql = re.sub(
                r"\b" + key + r" INTEGER PRIMARY KEY",
                key + " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                sql,
            )
        statements.append(sql)
    with schema_connection() as local:
        for name, sql in local.execute(
            "SELECT name,sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"
        ):
            table = re.search(r"\bON\s+(\w+)", sql, re.I).group(1)
            if table not in PRIVATE_TABLES:
                statements.append(sql)
        for name, sql in local.execute("SELECT name,sql FROM sqlite_master WHERE type='view'"):
            sql = sql.replace("CREATE VIEW IF NOT EXISTS", "CREATE VIEW").replace(
                "current_role", '"current_role"'
            )
            if name == "v_contact_crm":
                sql = sql.replace("GROUP BY p.person_id", "GROUP BY p.person_id,c.company_id")
            statements.append(sql)
    from crm.relationship_migration import view_statements

    statements.extend(view_statements())
    for table in APPEND_ONLY | {"crm_commits"}:
        statements.append(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION crm_immutable()"
        )
    return statements


def records(source):
    source.row_factory = sqlite3.Row
    return {
        table: [
            {column: public_value(table, column, row[column]) for column in row.keys()}
            for row in source.execute('SELECT * FROM "' + table + '"')
        ]
        for table in shared_tables()
    }


def fingerprint(rows):
    return hashlib.sha256(
        json.dumps(
            sorted([json.dumps(r, sort_keys=True, ensure_ascii=False) for r in rows]),
            ensure_ascii=False,
        ).encode()
    ).hexdigest()


def manifest(database):
    with sqlite3.connect(Path(database).resolve().as_uri() + "?mode=ro", uri=True) as source:
        assert source.execute("PRAGMA integrity_check").fetchall() == [("ok",)]
        assert not source.execute("PRAGMA foreign_key_check").fetchall()
        data = records(source)
    return {
        "schema": "crm_gtm",
        "schema_version": 1,
        "tables": {
            table: {"count": len(rows), "public_sha256": fingerprint(rows)}
            for table, rows in data.items()
        },
        "private_tables_excluded": sorted(PRIVATE_TABLES),
        "private_columns_sanitized": sorted(PRIVATE_COLUMNS),
        "local_history": "Original database, exact private values, evidence and backups retained locally",
    }, data


def migrate(dsn, database):
    import psycopg
    from psycopg import sql

    report, data = manifest(database)
    with psycopg.connect(dsn, connect_timeout=15, options="-c statement_timeout=60000") as remote:
        if remote.execute("SELECT to_regnamespace('crm_gtm') IS NOT NULL").fetchone()[0]:
            raise ValueError("crm_gtm already exists; refusing to overwrite or reimport")
        for statement in schema_sql():
            remote.execute(statement)
        for table, rows in data.items():
            if not rows:
                continue
            columns = list(rows[0])
            query = sql.SQL("INSERT INTO crm_gtm.{} ({}) VALUES ({})").format(
                sql.Identifier(table),
                sql.SQL(",").join(map(sql.Identifier, columns)),
                sql.SQL(",").join(sql.Placeholder() for _ in columns),
            )
            with remote.cursor() as cursor:
                cursor.executemany(
                    query, [tuple(row[column] for column in columns) for row in rows]
                )
        for table, key in IDENTITIES.items():
            remote.execute(
                sql.SQL(
                    "SELECT setval(pg_get_serial_sequence(%s,%s),COALESCE((SELECT max({}) FROM crm_gtm.{}),0)+1,false)"
                ).format(sql.Identifier(key), sql.Identifier(table)),
                ("crm_gtm." + table, key),
            )
        report["transactional_import"] = True
    report["verified"] = verify(dsn, data)
    return report


def verify(dsn, expected):
    import psycopg
    from psycopg import sql
    from psycopg.rows import dict_row

    with psycopg.connect(
        dsn, row_factory=dict_row, options="-c default_transaction_read_only=on"
    ) as remote:
        result = {}
        for table, rows in expected.items():
            actual = remote.execute(
                sql.SQL("SELECT * FROM crm_gtm.{}").format(sql.Identifier(table))
            ).fetchall()
            result[table] = {
                "count": len(actual),
                "matches": fingerprint(actual) == fingerprint(rows),
            }
        if not all(row["matches"] for row in result.values()):
            raise RuntimeError("Remote readback does not match reviewed manifest; cutover blocked")
    return result


def provision_operator(dsn, role, password):
    """Create a new operator restricted to CRM DML; never alter an existing role."""
    import psycopg
    from psycopg import sql

    if not re.fullmatch(r"crm_gtm_[a-z][a-z0-9_]{1,40}", role):
        raise ValueError("Dedicated CRM operator role required")
    with psycopg.connect(dsn, connect_timeout=15) as remote:
        if remote.execute("SELECT 1 FROM pg_roles WHERE rolname=%s", (role,)).fetchone():
            raise ValueError("Operator role already exists; refusing to change it")
        remote.execute(
            sql.SQL(
                "CREATE ROLE {} LOGIN PASSWORD {} NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION"
            ).format(sql.Identifier(role), sql.Literal(password))
        )
        remote.execute("REVOKE ALL ON SCHEMA crm_gtm FROM PUBLIC")
        remote.execute(sql.SQL("GRANT USAGE ON SCHEMA crm_gtm TO {}").format(sql.Identifier(role)))
        remote.execute(
            sql.SQL("GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA crm_gtm TO {}").format(
                sql.Identifier(role)
            )
        )
        remote.execute(
            sql.SQL("REVOKE INSERT,UPDATE ON crm_gtm.crm_backend_meta FROM {}").format(
                sql.Identifier(role)
            )
        )
        remote.execute(
            sql.SQL("REVOKE UPDATE ON crm_gtm.crm_commits FROM {}").format(sql.Identifier(role))
        )
        remote.execute(
            sql.SQL("GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA crm_gtm TO {}").format(
                sql.Identifier(role)
            )
        )
        remote.execute(
            sql.SQL("GRANT EXECUTE ON FUNCTION crm_gtm.crm_utc_now() TO {}").format(
                sql.Identifier(role)
            )
        )
        outside = remote.execute(
            "SELECT n.nspname,c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind='r' AND n.nspname IN ('public','neon_auth') AND has_table_privilege(%s,c.oid,'SELECT,INSERT,UPDATE,DELETE')",
            (role,),
        ).fetchall()
        if outside:
            raise RuntimeError(
                "Existing public grants expose non-CRM tables; operator role creation rolled back"
            )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", type=Path, default=ROOT / "data/crm.sqlite3")
    parser.add_argument("--credential-file", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    if args.output.exists():
        raise ValueError("Use a new report path")
    if args.apply:
        if not args.credential_file:
            parser.error("--apply requires an explicit credential file")
        result = migrate(args.credential_file.read_text().strip(), args.database)
    else:
        result, _ = manifest(args.database)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")
    print(
        json.dumps(
            {
                "tables": len(result["tables"]),
                "people": result["tables"]["people"]["count"],
                "applied": args.apply,
            }
        )
    )


if __name__ == "__main__":
    main()
