-- Preparation only. No send queue or automatic contacted-state updates.
CREATE TABLE IF NOT EXISTS email_reviews (
    review_id TEXT PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES contact_points(contact_id),
    exact_address TEXT NOT NULL,
    decision TEXT NOT NULL CHECK(decision IN ('draft_ok','hold')),
    source_url TEXT NOT NULL,
    reason TEXT NOT NULL,
    reviewed_at TEXT NOT NULL,
    gmail_account TEXT NOT NULL,
    history_query TEXT NOT NULL,
    history_result TEXT NOT NULL CHECK(history_result IN ('no_match','needs_review','unavailable')),
    history_checked_at TEXT NOT NULL,
    reviewer TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS email_preparations (
    preparation_id TEXT PRIMARY KEY,
    campaign TEXT NOT NULL,
    account TEXT NOT NULL,
    batch_day TEXT NOT NULL,
    person_id TEXT NOT NULL REFERENCES people(person_id),
    company_id TEXT NOT NULL REFERENCES companies(company_id),
    contact_id TEXT NOT NULL REFERENCES contact_points(contact_id),
    exact_address TEXT NOT NULL,
    address_key TEXT NOT NULL,
    review_id TEXT NOT NULL REFERENCES email_reviews(review_id),
    draft_id TEXT NOT NULL,
    revision INTEGER NOT NULL,
    variant TEXT NOT NULL CHECK(variant IN ('a','b')),
    assignment_method TEXT NOT NULL CHECK(assignment_method='editorial'),
    selection_reason TEXT NOT NULL,
    utm_enabled INTEGER NOT NULL CHECK(utm_enabled=0),
    utm_reason TEXT NOT NULL,
    state TEXT NOT NULL CHECK(state IN ('prepared','create_pending','gmail_draft')),
    gmail_draft_id TEXT,
    gmail_message_id TEXT,
    gmail_thread_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(draft_id,revision) REFERENCES copy_revisions(draft_id,revision),
    UNIQUE(campaign,account,person_id),
    UNIQUE(campaign,account,address_key),
    UNIQUE(account,gmail_draft_id)
);
